name: Test

on:
  push:
    branches:
      - main
      - master

jobs:
  echojobs:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: echo
        run: |
          echo "GH workflow"

