name: Test

on:
  workflow_dispatch:
    inputs:
      input:
        required: true

jobs:
  echojobs:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "GH workflow"

